export const CARTS_SERVICE = 'CARTS'
export const CARTS_UPDATE_PRODUCT_EVENT = 'CARTS_UPDATE_PRODUCT'

export const CARTS_DELETE_ITEMS_EVENT = 'CARTS_DELETE_ITEMS_EVENT'
export const CARTS_DELETE_ITEMS_BY_PROUCT_ID_EVENT = "CARTS_DELETE_ITEMS_BY_PROUCT_ID_EVENT"

export const WISHLIST_DELETE_ITEMS_BY_MERCHANT_ID_EVENT = "WISHLIST_DELETE_ITEMS_BY_MERCHANT_ID_EVENT"