export const ORDER_SERVICE = 'ORDER'
export const FINDONE_ORDER_EVENT = 'FINDONE_ORDER'
export const UPDATEREVIEW_ORDER_EVENT = "UPDATEREVIEW_ORDER"


export const ORDERING_EVENT = 'ORDERING_EVENT'
export const UPDATE_ORDER_STATUS_EVENT = 'UPDATE_ORDER_STATUS_EVENT'
export const UPDATE_STATUS_REFUND_EVENT = 'UPDATE_STATUS_REFUND_EVENT'