export const PAYMENT_SERVICE = "PAYMENT"


export const PAID_ORDERING_EVENT = "PAID_ORDERING_EVENT"

export const REFUND_CREDITCARD_EVENT = 'REFUND_CREDITCARD_EVENT'
export const RECEIVED_ORDER_EVENT = 'RECEIVED_ORDER_EVENT'