export const PRODUCTS_SERVICE = 'PRODUCTS'
export const PRODUCTS_ORDERING_EVENT = 'ORDERING'
export const CHARGE_MONTH_EVENT = "CHARGE_MONTH"
export const RETURN_STOCK_EVENT = "RETURN_STOCK"
export const PRODUCTS_TCP="PRODUCTS_TCP"
export const MERCHANT_DELETE_P = "MERCHANT_DELETE"