name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Check User
      run: whoami
    - name: Current directory
      run: pwd
    # - name: Sudo mode
    #   run: sudo -i
    - name: Test Docker command
      run: echo "user" | sudo -S docker ps
    - name: Check if Docker containers are running
      id: check-containers
      run: |
        CONTAINERS=$(echo "user" | sudo -S docker ps -a -q)
        if [[ -n "$CONTAINERS" ]]; then
          echo "Containers found. Stopping containers..."
          echo "::set-output name=containers_found::true"
        else
          echo "No containers found."
          echo "::set-output name=containers_found::false"
        fi
    - name: Stop Docker containers
      if: ${{ steps.check-containers.outputs.containers_found == 'true' }}
      run: |
        set -e
        echo "user" | sudo -S docker stop $(echo "user" | sudo -S docker ps -a -q) || true
    - name: Romove All Container
      if: ${{ steps.check-containers.outputs.containers_found == 'true' }}
      run: |
        set -e
        echo "user" | sudo -S docker rm $(echo "user" | sudo -S docker ps -a -q) || true
    - name: Rebuild Image
      run: echo "user" | sudo -S docker compose build --no-cache
    - name: Clean up system
      run: echo "user" | sudo -S docker system prune -f
    - name: Clean up volume
      run: echo "user" | sudo -S docker volume prune -f
    - name: Start Compose
      run: echo "user" | sudo -S docker compose -f 'docker-compose.dev.yml' up -d
